version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo "Install Prequisites"
      - npm install
      - npm install -g serverless@3.7.4
  build:
    commands:
      - echo "package servicex"
      - sls -version