version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo "Install Prequisites"
      - npm install --location=global serverless@3.24.1
  build:
    commands:
      - echo "package servicex"
      - cd infrastructure
      - sls package --package sls-bucket-sample --stage develop
      - ls sls-bucket-sample