version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo "Install Prequisites"
      - node --version
      - npm install -g serverless@3.24.1
  build:
    commands:
      - echo "package servicex"
      - sls -version