version: 0.2

phases:
  install:
    commands:
      - echo "Install Prequisites"
      - npm install
      - npm install -g serverless@3.7.4
  build:
    commands:
      - echo "package servicex"
      - . ./aws-profile-setup.sh
      - sls -version