version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run: git --version
      - run: docker --version
      - run: echo "construyendo..."
  test:
    docker:
      - image: ealen/echo-server
    steps:
      - run: echo "testeando..."

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
