version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    resource_class: small
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout
      - run: git --version
      - run: docker --version
      - run: docker build . -t mytag
      - run: touch my_file
  test:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run: ls -al

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
