version: 2.1

jobs:
  build:
    docker:
      - image: cimg/aws:2022.11
    resource_class: small
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout
      - run: export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn arn:aws:iam::328282054938:role/k8sDeployerRole --role-session-name $CIRCLE_PROJECT_REPONAME-session-$CIRCLE_BUILD_NUM --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))
      - run: | 
          aws sts get-caller-identity --no-cli-pager
          echo $RoleAccessKeyID
      - run: docker login --username AWS 328282054938.dkr.ecr.us-west-1.amazonaws.com -p $(aws ecr get-login-password --region us-west-1)
      - run: docker build . -t mytag
      - run: mkdir -p my_workspace
      - run: touch my_workspace/my_file
      - run: echo "testing echos" >> my_workspace/my_file
      - persist_to_workspace:
          root: my_workspace
          paths:
            - "my_file"
  test:
    docker:
      - image: cimg/base:2022.12
    steps:
      - attach_workspace:
          at: my_workspace
      - run: ls -al
      - run: cat my_workspace/my_file

workflows:
  build_and_test:
    jobs:
      - build:
          context: aws-credentials
      - test:
          requires:
            - build
