version: 2.1

jobs:
  build:
    docker:
      - image: cimg/aws:2022.11
    resource_class: small
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout
      - run: | 
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn $AWS_DEPLOYER_ROLE_ARN --role-session-name $CIRCLE_PROJECT_REPONAME-session-$CIRCLE_BUILD_NUM --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))
          docker login --username AWS 328282054938.dkr.ecr.us-west-1.amazonaws.com -p $(aws ecr get-login-password --region us-west-1)
      - run: docker build . -t mytag
      - run: mkdir -p my_workspace
      - run: touch my_workspace/my_file
      - run: echo "testing echos" >> my_workspace/my_file
      - persist_to_workspace:
          root: my_workspace
          paths:
            - "my_file"
  test:
    docker:
      - image: cimg/base:2022.12
    resource_class: small
    steps:
      - attach_workspace:
          at: my_workspace
      - run: ls -al
      - run: cat my_workspace/my_file
  deploy:
    docker:
      - image: cimg/aws:2022.11
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Installing Helm
          command: |
            curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
            sudo apt-get install apt-transport-https --yes
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
            sudo apt-get update
            sudo apt-get install helm
            helm version
            helm install release-$CIRCLE_BUILD_NUM sample-chart

workflows:
  build_and_test:
    jobs:
      - build:
          context: aws-credentials
      - test:
          requires:
            - build
      - deploy:
          context: aws-credentials
          requires:
            - "test"
