apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.app }}-deploy-blue'
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: '{{ .Values.app }}-blue'
        image: nginx:1.14.2
        ports:
        - containerPort: 80