AWSTemplateFormatVersion: "2010-09-09"
Description: Bucket created by deployer cross-account role.
Resources:
  MySampleBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties: 
      AccessControl: Private
      BucketName: serverless-private-bucket-cross-account
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
