AWSTemplateFormatVersion: 2010-09-09
Description: Bucket created by deployer cross-account role.
Resources:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties: 
    AccessControl: Private
    DeletionPolicy: Retain
    BucketName: ServerlessPrivateBucketCrossAccount